apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-ooox
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-ooox
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-ooox
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-ooox
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-ooox
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-czxo-tenant/rhtap-demo-app/hacbs-test-project-ooox@sha256:a7b9f81c4ae7893ed15131ca40c213d0fbc5c0b9d7a7f7456dffdd17c46fb0d4
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
